config/routes.rb
Rails.application.routes.draw do
  # get :tickets, to: 'tickets#show', as: :ticket

  get 'historic_prices/index'

  get 'inventories/index'

  get 'low_stock/index'

  get 'quotations/index'

  get 'foo/login'
  get 'foo/index'

  root 'farmacia#index'

  resources :aggregates
  resources :sales
  resources :wastes
  resources :tickets

  resources :transactions do
  end

  resources :box_movements

  resources :clients do
  get :autocomplete_client_rut, on: :collection
  end

  resources :clients do
    get :autocomplete_client_name, on: :collection
  end

  resources :products do
    get :autocomplete_product_name, on: :collection
    get :autocomplete_product_code, on: :collection
  end

  resources :presentations do
    get :autocomplete_presentation_name, on: :collection
  end

  resources :principles do
    get :autocomplete_principle_name, on: :collection
  end

  resources :categories do
    get :autocomplete_category_description, on: :collection
  end

  resources :laboratories do
    get :autocomplete_laboratory_name, on: :collection
  end

  resources :providers do
    get :autocomplete_provider_name, on: :collection
  end

  resources :offices do
    get :autocomplete_office_address, on: :collection
  end
  
  resources :aggregates do
    get :autocomplete_aggregates_product_code, on: :collection
  end

  get 'search/users', to: 'search_users#index', as: 'search_users'
  get 'search/products', to: 'search_products#index', as: 'search_products'
  get 'search/presentations', to: 'search_presentation#index', as: 'search_presentations'
  get 'search/categories', to: 'search_category#index', as: 'search_categories'
  get 'search/providers', to: 'search_provider#index', as: 'search_providers'
  get 'search/clients', to: 'search_client#index', as: 'search_clients'
  get 'search/principles', to: 'search_principle#index', as: 'search_principles'
  get 'search/laboratories', to: 'search_laboratory#index', as: 'search_laboratories'
  get 'search/offices', to: 'search_office#index', as: 'search_offices'
  get 'search/wastes', to: 'search_waste#index', as: 'search_wastes'
  get 'search/aggregates', to: 'search_aggregate#index', as: 'search_aggregates'


  resources :users

   scope :session do
     devise_for :users, controllers: { sessions: 'users/sessions',
                                       registrations: 'users/registrations' }

    put :rut, to: 'rut#update', as: 'set_rut'
    put :name, to: 'name#update', as: 'set_name'
  end

  resources :cart do
    resources :cart_item
  end
end

app/models/office.rb
class Office < ApplicationRecord
  has_many :users
  has_many :wastes
  has_many :products, inverse_of: :category
  
  has_one :inventory, autosave: true, dependent: :delete, inverse_of: :product
  accepts_nested_attributes_for :inventory

  validates :address, presence: { case_sensitive: false }
  validates :sii_code, presence: { case_sensitive: false }
  validates :phone, presence: { case_sensitive: false }
  validates :hour_in, presence: { case_sensitive: false }
  validates :hour_out, presence: { case_sensitive: false }

  scope :match_address, ->(address) do
    where('address ilike ?', "%#{address}%")
  end

end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  autocomplete :office, :address

  before_action :authenticate_user!

  def new
    @office = Office.new
  end

  def index
    @office = Office.all
  end

  def show
    @office = Office.find(params[:id])
  end


  def create
    puts "#{params[:office][:hour_in]}"


    @office = Office.new(address: params[:office][:address],
                         sii_code: params[:office][:sii_code],
                         phone: params[:office][:phone],
                         description: params[:office][:description],
                        )

    hora_entrada = params[:office]['hour_in(4i)']
    min_entrada = params[:office]['hour_in(5i)']

    hora_salida = params[:office]['hour_out(4i)']
    min_salida = params[:office]['hour_out(5i)']

    @office.hour_in = Time.parse(DateTime.parse("#{hora_entrada}:#{min_entrada}").to_s)
    @office.hour_out = Time.parse(DateTime.parse("#{hora_salida}:#{min_salida}").to_s)

    if @office.save
      flash[:notice] = "Cliente creado con exito"
      redirect_to @office
    else
      render :action => 'new'
    end
  end

  def edit
    @office = Office.find(params[:id])
  end

  def update
    @office = Office.find(params[:id])

    if @office.update(office_params)
      redirect_to @office
    else
      render 'edit'
    end
  end


  def destroy
    @office = Office.find(params[:id])

    begin
      @office.destroy
    rescue ActiveRecord::InvalidForeignKey
      return redirect_to root_path, alert: 'Esta Sucursal esta activa o genero ventas, no es posible eliminarlo'
    end

    redirect_to root_path, notice: 'Sucursal eliminada'
  end


  private
  def office_params
    params.require(:office).permit(:address, :sii_code, :phone, :description , :hour_in, :hour_out)
  end

end

app/views/offices/_office.html.erb
<tr>

  <td>
    <%= office.address %>
  </td>

  <td>
    <%= office.phone %>
  </td>
  
    <td>
    <%= office.sii_code %>
  </td>
  
    <td>
    <%= office.hour_in %>
  </td>
  
    <td>
    <%= office.hour_out %>
  </td>
  

  
  <td>
      <%= hidden_field_tag(:search_office_field, office.address) %>
      <%= button_tag '', type: 'submit', class: 'glyphicon glyphicon-ok' %>
  </td>

</tr>

app/views/offices/edit.html.erb
<% if @office.errors.any? %>
  <div class="alert alert-danger">
    <%= pluralize(@office.errors.count, "errors") %>

    <ul>
      <% @office.errors.full_messages.each do |message| %>
	<li>
	  <%= message %>
	</li>
      <% end %>
    </ul>
  </div>
<% end %>


<h1>Modificar Sucursal</h1>

<%= form_for(@office) do |f| %>

       <p>
         <%= f.label :address %><br>
         <%= f.text_field :address %>
       </p>
       <p>
         <%= f.label :sii_code %><br>
         <%= f.text_field :sii_code %>
       </p>
       <p>
         <%= f.label :phone %><br>
         <%= f.text_field :phone %>
       </p>


       <p>
         <%= f.label :description %><br>
         <%= f.text_field :description %>
       </p>


       <p>
         <%= f.label :hour_in %><br />
         <%= f.time_select :hour_in %>
       </p>


       <p>
         <%= f.label :hour_out %><br>
         <%= f.time_select :hour_out%>
       </p>





  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Atras', offices_path %>

app/views/offices/index.html.erb
<%= render 'partials/search_office/search_office' %>

app/views/offices/new.html.erb
<%= render 'partials/shared/list_errors', object: @office %>

<div class="panel panel-default">

  <div class="panel-heading">
    Crear Sucursal
  </div>

  <div class="panel-body">
    <%= form_for @office, method: :create do |f| %>
    <div class="row">

    <div class="col-md-4">

       <p>
	 <%= f.label :address %><br>
	 <%= f.text_field :address %>
       </p>
       <p>
	 <%= f.label :sii_code %><br>
	 <%= f.text_field :sii_code %>
       </p>
       <p>
	 <%= f.label :phone %><br>
	 <%= f.text_field :phone %>
       </p>


       <p>
	 <%= f.label :description %><br>
	 <%= f.text_field :description %>
       </p>


       <p>
	 <%= f.label :hour_in %><br />
	 <%= f.time_select :hour_in, :default => {:hour => '10', :minute => '30'}  %>
       </p>


       <p>
	 <%= f.label :hour_out %><br>
	 <%= f.time_select :hour_out, :default => {:hour => '10', :minute => '30'}  %>
       </p>


	   <p>
	    <%= f.submit %>
	   </p>
     </div>

     <% end %>
  </div>
 </div>
</div>

app/views/offices/show.html.erb
<%= render 'partials/offices/table', offices: [@office] %>