config/routes.rb
Rails.application.routes.draw do
  # get :tickets, to: 'tickets#show', as: :ticket

  get 'historic_prices/index'

  get 'inventories/index'

  get 'low_stock/index'

  get 'quotations/index'

  get 'foo/login'
  get 'foo/index'

  root 'farmacia#index'

  resources :aggregates
  resources :sales
  resources :wastes
  resources :tickets

  resources :transactions do
  end

  resources :box_movements

  resources :clients do
  get :autocomplete_client_rut, on: :collection
  end

  resources :clients do
    get :autocomplete_client_name, on: :collection
  end

  resources :products do
    get :autocomplete_product_name, on: :collection
    get :autocomplete_product_code, on: :collection
  end

  resources :presentations do
    get :autocomplete_presentation_name, on: :collection
  end

  resources :principles do
    get :autocomplete_principle_name, on: :collection
  end

  resources :categories do
    get :autocomplete_category_description, on: :collection
  end

  resources :laboratories do
    get :autocomplete_laboratory_name, on: :collection
  end

  resources :providers do
    get :autocomplete_provider_name, on: :collection
  end

  resources :offices do
    get :autocomplete_office_address, on: :collection
  end
  
  resources :aggregates do
    get :autocomplete_aggregates_product_code, on: :collection
  end

  get 'search/users', to: 'search_users#index', as: 'search_users'
  get 'search/products', to: 'search_products#index', as: 'search_products'
  get 'search/presentations', to: 'search_presentation#index', as: 'search_presentations'
  get 'search/categories', to: 'search_category#index', as: 'search_categories'
  get 'search/providers', to: 'search_provider#index', as: 'search_providers'
  get 'search/clients', to: 'search_client#index', as: 'search_clients'
  get 'search/principles', to: 'search_principle#index', as: 'search_principles'
  get 'search/laboratories', to: 'search_laboratory#index', as: 'search_laboratories'
  get 'search/offices', to: 'search_office#index', as: 'search_offices'
  get 'search/wastes', to: 'search_waste#index', as: 'search_wastes'
  get 'search/aggregates', to: 'search_aggregate#index', as: 'search_aggregates'


  resources :users

   scope :session do
     devise_for :users, controllers: { sessions: 'users/sessions',
                                       registrations: 'users/registrations' }

    put :rut, to: 'rut#update', as: 'set_rut'
    put :name, to: 'name#update', as: 'set_name'
  end

  resources :cart do
    resources :cart_item
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :setup_cart
  before_action :avoid_empty_cart, only: :create

  def index
    @transactions = Transaction.all
  end

  def show
    @transaction = Transaction.find params[:id]
  end

  def create
    
  end

  def ticket
    @transaction = Transaction.find params[:transaction_id]
    render 'ticket.txt.erb', layout: false
  end

  private

  def set_transaction_client
    rut = session[:client_rut]
    name = session[:client_name]

    @transaction.client = Client.from_rut(rut) if rut
    @transaction.client.name = name if name && rut
  end

  def avoid_empty_cart
    if @cart.empty?
      flash[:alert] = 'El carrito esta vacio!'
      redirect_back(fallback_location: new_cart_path)
    end
  end
end

app/views/transactions/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Historico ventas
  </div>

  <table class="table">
    <thead>
      <th>
	Numero transaccion
      </th>

      <th>
	Vendedor
      </th>

      <th>
	Fecha
      </th>

      <th>
	Monto transaccion
      </th>
    </thead>

    <tbody>
      <% @transactions.each  do |t| %>
	<tr>
	  <td>
	    <%= link_to t.id, transaction_path(t) %>
	  </td>

	  <td>
	    <%= link_to t.user.name, user_path(t.user) %>
	  </td>

	  <td>
	    <%= t.date %>
	  </td>

	  <td>
	    $<%= t.total %>
	  </td>
	</tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/transactions/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      Venta
    </div>
  </div>

  <div class="panel-body">
    <table class="table">
      <thead>
	<th>
	  N° de Venta
	</th>
	<th>
	  Fecha
	</th>
      </thead>

      <tbody>
	<tr>
	  <td>
	    <%= Transaction.last.id + 1 %>
	  </td>

	  <td>
	    <%= Time.now.to_formatted_s(:db) %>
	  </td>
	</tr>
      </tbody>

      <div class="row">
      </div>
    </table>

    <%= render 'partials/transactions/cart', products: [] %>

  </div>
</div>

app/views/transactions/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Venta
  </div>

  <div class="panel-body">
    <table class="table">
      <thead>
	<th>
	  #
	</th>

	<% if @transaction.client %>
	  <th>
	    Rut cliente
	  </th>
	<% end %>

	<th>
	  Fecha
	</th>

	<th>
	  Vendedor
	</th>

	<th>
	  IVA
	</th>

	<th>
	  Total
	</th>

	<th>
	  Pagado
	</th>
      </thead>

      <tbody>
	<tr>
	  <td>
	    <%= @transaction.id %>
	  </td>

	  <% if @transaction.client %>
	    <td>
	      <%= @transaction.client.rut %>
	    </td>
	  <% end %>

	  <td>
	    <%= @transaction.date %>
	  </td>

	  <td>
	    <%= @transaction.user.rut %>
	  </td>

	  <td>
	    <%= @transaction.iva %>
	  </td>

	  <td>
	    <%= @transaction.total %>
	  </td>

	  <td>
	    <%= @transaction.payed_amount %>
	  </td>
	</tr>
      </tbody>
    </table>
    <h3>
      Lista de productos
    </h3>

    <table class="table">
      <thead>
	<th>
	  #
	</th>

	<th>
	  Producto
	</th>

	<th>
	  Cantidad
	</th>

	<th>
	  Precio Bruto
	</th>

	<th>
	  Precio Neto
	</th>

	<th>
	  Devolucion
	</th>
      </thead>

      <tbody>
	<% for td in @transaction.details do %>
	  <tr>
	    <td>
	      <%= td.product.id %>
	    </td>

	    <td>
	      <%= td.product.name %>
	    </td>

	    <td>
	      <%= td.quantity %>
	    </td>

	    <td>
	      <%= td.unit_price %>
	    </td>

	    <td>
	      <%= td.net_price %>
	    </td>

	    <td>
	      <%= td.devolution %>
	    </td>
	  </tr>
	<% end %>
      </tbody>
    </table>

    <%= form_tag ticket_path(@transaction), method: :get do %>
      <%= submit_tag('Boleta', class: 'btn btn-default') %>
    <% end %>
  </div>
</div>

app/views/transactions/ticket.txt.erb
"Farmacias Herrera"
IMP. COMER. Y DISTRIB. DE PRODUCTOS
FARMACEUTICOS Y PERFUMERIA.
C. MATRIZ:AV.FROILAN ROA 580 LOCAL 7,
LA FLORIDA.



Rut Nro.: 76.133.541-3
FARMACIAS HERRERA LTDA.


**BOLETA DE VENTA AUTORIZADA POR EL SII***
**   RES. EX. No. 94 del 30/09/2004    ***

Numero de caja: <%= Box.get_box.id %>
Nro. Boleta: <%= @transaction.id %>
Fecha <%= @transaction.date %>

<% @transaction.details.each do |d| %>
<%= d.product.name %>     <%= d.quantity  %> x <%= d.net_price %>   <%= d.quantity * d.net_price %>
<% end %>


TOTAL: <%= @transaction.total %>
<% if @transaction.change %>
VUELTO: <%= @transaction.change %>
<% end %>